// Shared inline styles for the Commercial admin screens. Kept local so the
// module adds no new CSS module and touches no existing stylesheet.
export const S = {
  page: { padding: "1.5rem" },
  h1: { fontSize: "1.35rem", fontWeight: 700, margin: 0 },
  sub: { color: "var(--fg-4)", fontSize: "0.85rem", marginTop: "0.25rem" },
  card: {
    background: "var(--bg-surface)",
    border: "1px solid var(--border)",
    borderRadius: 12,
    padding: "1rem 1.25rem",
    marginBottom: "1rem",
  },
  row: { display: "flex", gap: "0.75rem", alignItems: "center", flexWrap: "wrap" },
  input: {
    padding: "0.5rem 0.7rem",
    border: "1px solid var(--border-strong)",
    borderRadius: 8,
    fontSize: "0.85rem",
  },
  btn: {
    padding: "0.5rem 0.9rem",
    borderRadius: 8,
    border: "1px solid var(--accent)",
    background: "var(--accent)",
    color: "#fff",
    fontSize: "0.82rem",
    fontWeight: 600,
    cursor: "pointer",
  },
  btnGhost: {
    padding: "0.5rem 0.9rem",
    borderRadius: 8,
    border: "1px solid var(--border-strong)",
    background: "var(--bg-surface)",
    color: "var(--fg-3)",
    fontSize: "0.82rem",
    fontWeight: 600,
    cursor: "pointer",
  },
  table: { width: "100%", borderCollapse: "collapse", fontSize: "0.85rem" },
  th: {
    textAlign: "left",
    padding: "0.6rem 0.5rem",
    borderBottom: "2px solid var(--border)",
    color: "var(--fg-3)",
    fontSize: "0.72rem",
    textTransform: "uppercase",
    letterSpacing: "0.04em",
  },
  td: { padding: "0.55rem 0.5rem", borderBottom: "1px solid var(--bg-muted)" },
  scroll: { overflowX: "auto" },
  notice: {
    background: "var(--warning-bg)",
    border: "1px solid var(--warning)",
    color: "var(--warning-fg)",
    borderRadius: 10,
    padding: "0.85rem 1rem",
    fontSize: "0.85rem",
    marginBottom: "1rem",
  },
};
