/**
 * ============================================================================
 * AapliSociety RBAC — Canonical Permission Catalog
 * ============================================================================
 * SINGLE SOURCE OF TRUTH for every permission in the system.
 *
 * Permission id format:  <module>.<resource>.<action>   (camelCase segments)
 *   - Page-access permission for a page  ->  <module>.<pageKey>.view
 *   - Business/action permission         ->  <module>.<resource>.<action>
 *   - Wildcards (authoring only)          ->  <module>.<resource>.*  |  <module>.*
 *     (there is NO global "*" — deny-by-default forbids it)
 *
 * Every page in the app MUST appear here with `page: true` so the CI guard
 * (scripts/check-permission-registry.js) can prove no page ships without a
 * page-access permission. Every destructive/irreversible action MUST set
 * `dangerous: true` so the admin picker can surface a ⚠ indicator.
 *
 * Plugins/future modules do NOT edit this file. They call
 * registry.registerModule(moduleDef) at boot (see lib/rbac/registry.js).
 * ============================================================================
 */

/** @typedef {{ key:string, label:string, dangerous?:boolean, description?:string }} ActionDef */
/** @typedef {{ key:string, label:string, page?:boolean, path?:string, actions:ActionDef[] }} ResourceDef */
/** @typedef {{ key:string, label:string, resources:ResourceDef[] }} ModuleDef */

const view = { key: "view", label: "View" };
const create = { key: "create", label: "Create" };
const update = { key: "update", label: "Update" };
const del = { key: "delete", label: "Delete", dangerous: true };
const exportAct = { key: "export", label: "Export", dangerous: true };

/** @type {ModuleDef[]} */
export const PERMISSION_CATALOG = [
  // ── DASHBOARD ────────────────────────────────────────────────────────────
  {
    key: "dashboard",
    label: "Dashboard",
    resources: [
      {
        key: "admin",
        label: "Admin Dashboard",
        page: true,
        path: "/admin/dashboard",
        actions: [view],
      },
      { key: "stats", label: "Dashboard Stats", actions: [view] },
    ],
  },

  // ── BILLING ──────────────────────────────────────────────────────────────
  {
    key: "billing",
    label: "Billing & Finance",
    resources: [
      {
        key: "dashboard",
        label: "Billing Dashboard",
        page: true,
        path: "/admin/generate-bills",
        actions: [view],
      },
      {
        key: "generatedBills",
        label: "Generated Bills Page",
        page: true,
        path: "/admin/generated-bills",
        actions: [view],
      },
      {
        key: "viewBills",
        label: "View Bills Page",
        page: true,
        path: "/admin/view-bills",
        actions: [view],
      },
      {
        key: "importBills",
        label: "Import Bills Page",
        page: true,
        path: "/admin/import-bills",
        actions: [view],
      },
      {
        key: "bill",
        label: "Bills",
        actions: [
          view,
          { key: "generate", label: "Generate Bills" },
          { key: "import", label: "Import Bills", dangerous: true },
          { key: "update", label: "Update Bill" },
          { key: "delete", label: "Delete Bill", dangerous: true },
          { key: "markOverdue", label: "Mark Overdue" },
          { key: "download", label: "Download / PDF" },
          exportAct,
        ],
      },
      {
        key: "config",
        label: "Billing Configuration",
        page: true,
        path: "/admin/billing-config",
        actions: [
          view,
          { key: "update", label: "Update Billing Config", dangerous: true },
        ],
      },
      {
        key: "template",
        label: "Bill Template",
        page: true,
        path: "/admin/bill-template",
        actions: [
          view,
          { key: "update", label: "Update Template" },
          { key: "upload", label: "Upload Template Asset" },
        ],
      },
      {
        key: "head",
        label: "Billing Heads",
        actions: [view, create, update, del],
      },
      {
        key: "balanceSheet",
        label: "Balance Sheet",
        page: true,
        path: "/admin/balance-sheet",
        actions: [view, exportAct],
      },
      {
        key: "simulator",
        label: "Billing Simulator Page",
        page: true,
        path: "/admin/billing-simulator",
        actions: [view, { key: "run", label: "Run Simulation" }],
      },
    ],
  },

  // ── PAYMENTS / RECEIPTS / LEDGER ─────────────────────────────────────────
  {
    key: "finance",
    label: "Payments & Ledger",
    resources: [
      {
        key: "payments",
        label: "Payments Page",
        page: true,
        path: "/admin/payments",
        actions: [view],
      },
      {
        key: "receipts",
        label: "Receipts Page",
        page: true,
        path: "/admin/receipts",
        actions: [view],
      },
      {
        key: "latePayment",
        label: "Late Payment Page",
        page: true,
        path: "/admin/late-payment",
        actions: [view],
      },

      {
        key: "payment",
        label: "Payments",
        actions: [
          view,
          { key: "record", label: "Record Payment" },
          { key: "upload", label: "Upload Payments", dangerous: true },
          del,
          exportAct,
        ],
      },
      {
        key: "receipt",
        label: "Receipts",
        actions: [view, { key: "download", label: "Download Receipt" }],
      },
      {
        key: "ledger",
        label: "Ledger",
        page: true,
        path: "/admin/ledger",
        actions: [
          view,
          { key: "transaction", label: "Create Transaction" },
          {
            key: "calculateInterest",
            label: "Calculate Interest",
            dangerous: true,
          },
          exportAct,
        ],
      },
      {
        key: "societyEntry",
        label: "Society Financial-Year Entries",
        actions: [view, create, del],
      },
      {
        key: "expenditure",
        label: "Expenditure Page",
        page: true,
        path: "/admin/expenditure",
        actions: [view, create, update, del],
      },
      {
        key: "paymentsReceived",
        label: "Payments Received Page",
        page: true,
        path: "/admin/payments-received",
        actions: [view],
      },
    ],
  },

  // ── FINANCIAL STATEMENTS ─────────────────────────────────────────────────
  {
    key: "statements",
    label: "Financial Statements",
    resources: [
      {
        key: "openingBalances",
        label: "Opening Balances Page",
        page: true,
        path: "/admin/opening-balances",
        actions: [view, update],
      },
      {
        key: "generateStatements",
        label: "Generate Statements Page",
        page: true,
        path: "/admin/generate-statements",
        actions: [view, { key: "generate", label: "Generate Statements" }],
      },
      {
        key: "incomeExpenditure",
        label: "Income & Expenditure Page",
        page: true,
        path: "/admin/income-expenditure",
        actions: [view, exportAct],
      },
      {
        key: "assetsLiabilities",
        label: "Assets & Liabilities Page",
        page: true,
        path: "/admin/assets-liabilities",
        actions: [view, exportAct],
      },
      {
        key: "otherStatements",
        label: "Trial Balance & Validation Page",
        page: true,
        path: "/admin/other-statements",
        actions: [view, exportAct],
      },
    ],
  },

  // ── COMMERCIAL (shops/offices module) ────────────────────────────────────
  {
    key: "commercial",
    label: "Commercial",
    resources: [
      {
        key: "admin",
        label: "Commercial Page",
        page: true,
        path: "/admin/commercial",
        actions: [view, create, update, del],
      },
    ],
  },

  // ── AMENITIES ─────────────────────────────────────────────────────────────
  {
    key: "amenities",
    label: "Amenities",
    resources: [
      {
        key: "admin",
        label: "Amenities Page",
        page: true,
        path: "/admin/amenities",
        actions: [view, create, update, del],
      },
      // The Clubhouse Manager mobile environment. These are the leaves the
      // /api/v1/clubhouse/* routes check, one per kind of thing a manager does
      // on shift. Separate leaves rather than one "clubhouse.manage" so an
      // Admin can hand out the scan desk without also handing out maintenance
      // or society-wide notices.
      //
      // There is deliberately NO capacity action here. Capacity is
      // configuration-level infrastructure behind amenities.admin.*; no grant
      // in this resource can produce a capacity write.
      {
        key: "clubhouse",
        label: "Clubhouse Manager (mobile)",
        actions: [
          view,
          { key: "checkIn", label: "Scan & record attendance" },
          { key: "operate", label: "Open/close, timings & breaks" },
          { key: "maintenance", label: "Log & update maintenance" },
          { key: "incident", label: "Raise & resolve incidents" },
          { key: "notice", label: "Publish notices" },
        ],
      },
      // Resident amenity cards. Admin custody only: identify a scanned card,
      // and revoke one. Revoking is dangerous — a revoked card is how a
      // resident finds themselves refused at the door.
      {
        key: "memberCard",
        label: "Resident Amenity Cards",
        page: true,
        path: "/admin/amenities/cards",
        actions: [
          view,
          { key: "revoke", label: "Revoke a card", dangerous: true },
        ],
      },
    ],
  },

  // ── MEMBERS ──────────────────────────────────────────────────────────────
  {
    key: "member",
    label: "Members",
    resources: [
      {
        key: "viewMembers",
        label: "View Members Page",
        page: true,
        path: "/admin/view-members",
        actions: [view],
      },
      {
        key: "importMembers",
        label: "Import Members Page",
        page: true,
        path: "/admin/import-members",
        actions: [view],
      },
      {
        key: "profileEditRequests",
        label: "Profile Edit Requests Page",
        page: true,
        path: "/admin/profile-edit-requests",
        actions: [view],
      },
      {
        key: "tenantRequests",
        label: "Tenant Requests Page",
        page: true,
        path: "/admin/tenant-requests",
        actions: [view],
      },

      {
        key: "member",
        label: "Member Records",
        actions: [
          view,
          create,
          update,
          del,
          { key: "import", label: "Import Members", dangerous: true },
          {
            key: "downloadCredentials",
            label: "Download Credentials",
            dangerous: true,
          },
          {
            key: "resetPassword",
            label: "Reset Member Password",
            dangerous: true,
          },
          exportAct,
        ],
      },
      {
        key: "profileEditRequest",
        label: "Profile Edit Requests",
        actions: [
          view,
          { key: "approve", label: "Approve" },
          { key: "reject", label: "Reject" },
        ],
      },
      {
        key: "tenantRequest",
        label: "Tenant Requests",
        actions: [
          view,
          { key: "approve", label: "Approve" },
          { key: "reject", label: "Reject" },
          { key: "confirmMoveOut", label: "Confirm Move-Out", dangerous: true },
        ],
      },
      {
        key: "profile",
        label: "Member Self-Service Profile",
        actions: [
          { key: "viewSelf", label: "View Own Profile" },
          { key: "updateSelf", label: "Update Own Profile" },
        ],
      },
    ],
  },

  // ── COMPLAINTS ───────────────────────────────────────────────────────────
  {
    key: "complaint",
    label: "Complaints",
    resources: [
      {
        key: "admin",
        label: "Complaints Page",
        page: true,
        path: "/admin/complaints",
        actions: [view],
      },
      {
        key: "complaint",
        label: "Complaints",
        actions: [
          view,
          create,
          { key: "reply", label: "Reply" },
          { key: "approve", label: "Approve" },
          { key: "reject", label: "Reject" },
          { key: "close", label: "Close / Auto-close" },
        ],
      },
    ],
  },

  // ── NOTICES ──────────────────────────────────────────────────────────────
  {
    key: "notice",
    label: "Notices",
    resources: [
      {
        key: "admin",
        label: "Notices Page",
        page: true,
        path: "/admin/notices",
        actions: [view],
      },
      { key: "notice", label: "Notices", actions: [view, create, update, del] },
    ],
  },

  // ── VISITORS / SECURITY GATE ─────────────────────────────────────────────
  {
    key: "visitor",
    label: "Visitor Management",
    resources: [
      {
        key: "admin",
        label: "Visitors Page",
        page: true,
        path: "/admin/visitors",
        actions: [view],
      },
      {
        key: "active",
        label: "Active Visitors Page",
        page: true,
        path: "/admin/visitors/active",
        actions: [view],
      },
      {
        key: "log",
        label: "Visitor Log Page",
        page: true,
        path: "/admin/visitors/log",
        actions: [view],
      },
      {
        key: "audit",
        label: "Visitor Audit Page",
        page: true,
        path: "/admin/visitors/audit",
        actions: [view],
      },
      {
        key: "gate",
        label: "Security Gate Console",
        page: true,
        path: "/security/dashboard",
        actions: [view],
      },

      {
        key: "visitor",
        label: "Visitor Records",
        actions: [
          view,
          { key: "enter", label: "Log Entry" },
          { key: "exit", label: "Log Exit" },
          { key: "approve", label: "Approve" },
          { key: "extend", label: "Extend" },
          { key: "offlineEntry", label: "Offline Entry", dangerous: true },
          { key: "guardAdmit", label: "Guard Admit", dangerous: true },
          { key: "sos", label: "Raise SOS" },
        ],
      },
      {
        key: "pass",
        label: "Visitor Passes",
        actions: [view, create, { key: "verify", label: "Verify Pass" }, del],
      },
      {
        key: "blacklist",
        label: "Watchlist Page",
        page: true,
        path: "/admin/blacklist",
        actions: [
          view,
          { key: "add", label: "Add to Blacklist", dangerous: true },
          { key: "remove", label: "Remove", dangerous: true },
        ],
      },
    ],
  },

  // ── SECURITY GUARD MANAGEMENT ────────────────────────────────────────────
  {
    key: "security",
    label: "Security Staff",
    resources: [
      {
        key: "guards",
        label: "Security Guards Page",
        page: true,
        path: "/admin/security-guards",
        actions: [view],
      },
      {
        key: "guard",
        label: "Security Guards",
        actions: [
          view,
          create,
          update,
          del,
          { key: "resetPin", label: "Reset PIN", dangerous: true },
        ],
      },
    ],
  },

  // ── SOCIETY CONFIG ───────────────────────────────────────────────────────
  {
    key: "society",
    label: "Society Configuration",
    resources: [
      {
        key: "databaseManager",
        label: "Database Manager Page",
        page: true,
        path: "/admin/database-manager",
        actions: [view],
      },
      {
        key: "config",
        label: "Society Settings",
        page: true,
        path: "/admin/society-config",
        actions: [
          view,
          { key: "update", label: "Update Society Config", dangerous: true },
        ],
      },
      {
        key: "data",
        label: "Raw Data (Database Manager)",
        actions: [
          view,
          { key: "import", label: "Import Data", dangerous: true },
          exportAct,
          { key: "reset", label: "Reset Entity", dangerous: true },
          del,
        ],
      },
      {
        key: "systemTests",
        label: "System Test Tools Page",
        page: true,
        path: "/admin/accounting-lab",
        // "update" backs both the lab's own write actions AND the ~31
        // accounting/* engine API routes it is currently the only real
        // consumer of (no production admin page exists for those yet —
        // see lib/rbac/page-access-map.js systemTests entry).
        actions: [view, { key: "update", label: "Run / Modify Test Data", dangerous: true }],
      },
    ],
  },

  // ── AUDIT & COMPLIANCE ───────────────────────────────────────────────────
  {
    key: "audit",
    label: "Audit & Compliance",
    resources: [
      {
        key: "page",
        label: "Audit Page",
        page: true,
        path: "/admin/audit",
        actions: [view],
      },
      {
        key: "log",
        label: "Audit Log",
        actions: [{ key: "read", label: "Read Audit Log" }, exportAct],
      },
      { key: "report", label: "Audit Reports", actions: [view, create] },
    ],
  },

  // ── RBAC ADMIN (role & permission management) ────────────────────────────
  {
    key: "rbac",
    label: "Roles & Permissions",
    resources: [
      // Shared page — EVERY authenticated user can view their OWN access here.
      // Granted implicitly to all contexts (see system-role-defaults + member caps).
      {
        key: "myAccess",
        label: "My Roles & Permissions Page",
        page: true,
        path: "/my-access",
        actions: [view],
      },
      // Admin-only role management surface.
      {
        key: "roleManager",
        label: "Role Manager Page",
        page: true,
        path: "/admin/rbac/roles",
        actions: [view],
      },
      {
        key: "role",
        label: "Roles",
        actions: [
          view,
          create,
          update,
          { key: "clone", label: "Clone Role" },
          { key: "delete", label: "Delete Custom Role", dangerous: true },
          {
            key: "restoreDefaults",
            label: "Restore Template Defaults",
            dangerous: true,
          },
        ],
      },
      {
        key: "assignment",
        label: "Role Assignments",
        actions: [
          view,
          { key: "assign", label: "Assign Role", dangerous: true },
          { key: "unassign", label: "Unassign Role", dangerous: true },
        ],
      },
      {
        key: "user",
        label: "User Access Lifecycle",
        actions: [
          view,
          { key: "create", label: "Create Login User" },
          { key: "suspend", label: "Suspend User", dangerous: true },
          { key: "reactivate", label: "Reactivate User" },
        ],
      },
    ],
  },
];

export default PERMISSION_CATALOG;
