/**
 * ============================================================================
 * AapliSociety RBAC — Canonical Permission Catalog
 * ============================================================================
 * SINGLE SOURCE OF TRUTH for every permission in the system.
 *
 * Permission id format:  <module>.<resource>.<action>   (camelCase segments)
 *   - Page-access permission for a page  ->  <module>.<pageKey>.view
 *   - Business/action permission         ->  <module>.<resource>.<action>
 *   - Wildcards (authoring only)          ->  <module>.<resource>.*  |  <module>.*
 *     (there is NO global "*" — deny-by-default forbids it)
 *
 * Every page in the app MUST appear here with `page: true` so the CI guard
 * (scripts/check-permission-registry.js) can prove no page ships without a
 * page-access permission. Every destructive/irreversible action MUST set
 * `dangerous: true` so the admin picker can surface a ⚠ indicator.
 *
 * Plugins/future modules do NOT edit this file. They call
 * registry.registerModule(moduleDef) at boot (see lib/rbac/registry.js).
 * ============================================================================
 */

/** @typedef {{ key:string, label:string, dangerous?:boolean, description?:string }} ActionDef */
/** @typedef {{ key:string, label:string, page?:boolean, path?:string, actions:ActionDef[] }} ResourceDef */
/** @typedef {{ key:string, label:string, resources:ResourceDef[] }} ModuleDef */

const view = { key: "view", label: "View" };
const create = { key: "create", label: "Create" };
const update = { key: "update", label: "Update" };
const del = { key: "delete", label: "Delete", dangerous: true };
const exportAct = { key: "export", label: "Export", dangerous: true };

/** @type {ModuleDef[]} */
export const PERMISSION_CATALOG = [
  // ── DASHBOARD ────────────────────────────────────────────────────────────
  {
    key: "dashboard",
    label: "Dashboard",
    resources: [
      {
        key: "admin",
        label: "Admin Dashboard",
        page: true,
        path: "/admin/dashboard",
        actions: [view],
      },
      { key: "stats", label: "Dashboard Stats", actions: [view] },
    ],
  },

  // ── BILLING ──────────────────────────────────────────────────────────────
  {
    key: "billing",
    label: "Billing & Finance",
    resources: [
      {
        key: "dashboard",
        label: "Billing Dashboard",
        page: true,
        path: "/admin/generate-bills",
        actions: [view],
      },
      {
        key: "generatedBills",
        label: "Generated Bills Page",
        page: true,
        path: "/admin/generated-bills",
        actions: [view],
      },
      {
        key: "viewBills",
        label: "View Bills Page",
        page: true,
        path: "/admin/view-bills",
        actions: [view],
      },
      {
        key: "importBills",
        label: "Import Bills Page",
        page: true,
        path: "/admin/import-bills",
        actions: [view],
      },
      {
        key: "bill",
        label: "Bills",
        actions: [
          view,
          { key: "generate", label: "Generate Bills" },
          { key: "import", label: "Import Bills", dangerous: true },
          { key: "update", label: "Update Bill" },
          { key: "delete", label: "Delete Bill", dangerous: true },
          { key: "markOverdue", label: "Mark Overdue" },
          { key: "download", label: "Download / PDF" },
          exportAct,
        ],
      },
      {
        key: "config",
        label: "Billing Configuration",
        page: true,
        path: "/admin/billing-config",
        actions: [
          view,
          { key: "update", label: "Update Billing Config", dangerous: true },
        ],
      },
      {
        key: "template",
        label: "Bill Template",
        page: true,
        path: "/admin/bill-template",
        actions: [
          view,
          { key: "update", label: "Update Template" },
          { key: "upload", label: "Upload Template Asset" },
        ],
      },
      {
        key: "head",
        label: "Billing Heads",
        actions: [view, create, update, del],
      },
      {
        key: "balanceSheet",
        label: "Balance Sheet",
        page: true,
        path: "/admin/balance-sheet",
        actions: [view, exportAct],
      },
      {
        key: "simulator",
        label: "Billing Simulator Page",
        page: true,
        path: "/admin/billing-simulator",
        actions: [view, { key: "run", label: "Run Simulation" }],
      },
    ],
  },

  // ── PAYMENTS / RECEIPTS / LEDGER ─────────────────────────────────────────
  {
    key: "finance",
    label: "Payments & Ledger",
    resources: [
      {
        key: "payments",
        label: "Payments Page",
        page: true,
        path: "/admin/payments",
        actions: [view],
      },
      {
        key: "receipts",
        label: "Receipts Page",
        page: true,
        path: "/admin/receipts",
        actions: [view],
      },
      {
        key: "latePayment",
        label: "Late Payment Page",
        page: true,
        path: "/admin/late-payment",
        actions: [view],
      },

      {
        key: "payment",
        label: "Payments",
        actions: [
          view,
          { key: "record", label: "Record Payment" },
          { key: "upload", label: "Upload Payments", dangerous: true },
          del,
          exportAct,
        ],
      },
      {
        key: "receipt",
        label: "Receipts",
        actions: [view, { key: "download", label: "Download Receipt" }],
      },
      {
        key: "ledger",
        label: "Ledger",
        page: true,
        path: "/admin/ledger",
        actions: [
          view,
          { key: "transaction", label: "Create Transaction" },
          {
            key: "calculateInterest",
            label: "Calculate Interest",
            dangerous: true,
          },
          exportAct,
        ],
      },
      {
        key: "societyEntry",
        label: "Society Financial-Year Entries",
        actions: [view, create, del],
      },
      {
        key: "expenditure",
        label: "Expenditure Page",
        page: true,
        path: "/admin/expenditure",
        actions: [view, create, update, del],
      },
      {
        key: "paymentsReceived",
        label: "Payments Received Page",
        page: true,
        path: "/admin/payments-received",
        actions: [view],
      },
    ],
  },

  // ── FINANCIAL STATEMENTS ─────────────────────────────────────────────────
  {
    key: "accounting",
    label: "Accounting",
    resources: [
      {
        key: "overview",
        label: "Accounting Overview Page",
        page: true,
        path: "/admin/accounting",
        actions: [view],
      },
      {
        key: "setup",
        label: "Guided Setup Page",
        page: true,
        path: "/admin/accounting/setup",
        actions: [view, { key: "run", label: "Run a setup step" }],
      },
      {
        key: "chartOfAccounts",
        label: "Chart of Accounts Page",
        page: true,
        path: "/admin/accounting/chart-of-accounts",
        // Delete now exists, but only ever reaches an account the lock
        // matrix (lib/accounting/lockMatrix.js) has already cleared — an
        // account with journal lines, a fiscal mapping, or a posting-rule
        // reference is refused server-side regardless of this permission.
        // This grants the ABILITY to attempt a delete; the matrix decides
        // whether any given account is actually deletable.
        actions: [
          view,
          create,
          update,
          { key: "deactivate", label: "Deactivate an account head", dangerous: true },
          { key: "delete", label: "Delete an unposted account head", dangerous: true },
        ],
      },
      {
        key: "financialYears",
        label: "Financial Years Page",
        page: true,
        path: "/admin/accounting?drawer=financial-years",
        // No delete. A Financial Year with entries posted against it is not a
        // thing anyone should be able to remove from a screen — closing and
        // reopening are the reversible operations, and both are recorded in
        // the year's own transition history.
        actions: [
          view,
          { key: "create", label: "Create Financial Year" },
          { key: "close", label: "Close Financial Year", dangerous: true },
          { key: "reopen", label: "Reopen a closed Financial Year", dangerous: true },
        ],
      },
      // The three seeded registries below are the shared default tier
      // (societyId: null). Their services return 409 on any attempt to patch
      // a default-tier row, so these pages report and explain rather than
      // edit — hence view-only. A society that genuinely needs different
      // treatment adds an override, which is accountant's work and not yet
      // a screen.
      {
        key: "postingRules",
        label: "Automatic Entry Rules Page",
        page: true,
        path: "/admin/accounting?drawer=posting-rules",
        // The page itself only ever reads + calls setup.run's "install
        // defaults" step — a per-society override screen was never built.
        // The write routes (create/update/delete an override, reseed
        // defaults) are real and existed with no permission but the Lab's;
        // granted here so closing that hole doesn't need a page to exist
        // first, same as funds/liabilities/bankAccounts above.
        actions: [
          view,
          { key: "override", label: "Create or edit a per-society override" },
          { key: "seedDefaults", label: "Reseed the shared default rules", dangerous: true },
        ],
      },
      {
        key: "validationRules",
        label: "Book Checks Page",
        page: true,
        path: "/admin/accounting?drawer=validation-rules",
        actions: [
          view,
          { key: "override", label: "Create or edit a per-society override" },
          { key: "seedDefaults", label: "Reseed the shared default rules", dangerous: true },
        ],
      },
      {
        key: "schedules",
        label: "Statement Layout Page",
        page: true,
        path: "/admin/accounting?drawer=schedules",
        actions: [
          view,
          { key: "override", label: "Create a per-society schedule" },
          { key: "seedDefaults", label: "Reseed the shared default schedules", dangerous: true },
        ],
      },
      {
        key: "vouchers",
        label: "Entries (Vouchers) Page",
        page: true,
        path: "/admin/accounting/books?tab=entries",
        // Phase 5. Before this, every voucher workflow route carried only the
        // legacy requireAccounting()/requireAccountingClose() hat check — and
        // that helper waves through ANY RBAC staff token by design, on the
        // documented assumption that a real authorize() call follows it. On
        // these six routes none did, so a guard's staff token could reverse a
        // posted voucher. These are the permissions that close that.
        actions: [
          view,
          { key: "create", label: "Record an entry" },
          { key: "submit", label: "Send an entry for approval" },
          { key: "approve", label: "Approve an entry" },
          { key: "reject", label: "Reject an entry" },
          { key: "cancel", label: "Cancel a draft entry", dangerous: true },
          { key: "reverse", label: "Reverse a posted entry", dangerous: true },
        ],
      },
      {
        key: "journalEntries",
        label: "The Books (Journal Entries) Page",
        page: true,
        path: "/admin/accounting/books?tab=books",
        // Read-only. A posted figure is corrected by adding an offsetting
        // entry, never by rewriting it — so there is no update action to
        // grant, and the POST that posts a manual journal stays with
        // accounting.vouchers.create, where the writing screens live.
        actions: [view],
      },
      {
        key: "assets",
        label: "Asset Register Page",
        page: true,
        path: "/admin/accounting/assets",
        // The lab's step 3, which had no page of its own — it was the one
        // capability blocking the lab's retirement. Every action but
        // "transfer" posts to the ledger, which is why they are separate
        // permissions rather than one "manage".
        actions: [
          view,
          { key: "register", label: "Register an asset" },
          { key: "depreciate", label: "Run depreciation" },
          { key: "transfer", label: "Move an asset or change who holds it" },
          // Irreversible in the sense that matters: it posts a disposal
          // entry, closes the asset, and books a gain or loss. Undoing it
          // means reversing that entry.
          { key: "dispose", label: "Dispose of an asset", dangerous: true },
        ],
      },
      {
        key: "auditTrail",
        label: "Corrections (Audit Trail) Page",
        page: true,
        path: "/admin/accounting/books?tab=corrections",
        // Append-only by model: JournalAuditTrail has no update path and no
        // isDeleted. View is the only thing there is to grant.
        actions: [view],
      },
      // Below: FundService/LiabilityService/BankAccountService/
      // BankReconciliationService/FiscalConfigService were fully built (§3,
      // §8, §6.4, §6.11) with no admin page ever wired to them — every route
      // ran on "society.systemTests.*" alone, the Lab's permission, because
      // that was the only thing that ever called them. Real permissions
      // added here alongside the new pages that actually use them.
      {
        key: "funds",
        label: "Funds Page",
        page: true,
        path: "/admin/accounting/funds",
        actions: [
          view,
          { key: "create", label: "Register a fund" },
          { key: "contribute", label: "Contribute to a fund" },
          { key: "withdraw", label: "Withdraw from a fund", dangerous: true },
          { key: "transfer", label: "Transfer between funds", dangerous: true },
        ],
      },
      {
        key: "liabilities",
        label: "Liabilities Page",
        page: true,
        path: "/admin/accounting/liabilities",
        actions: [
          view,
          { key: "incur", label: "Record a liability" },
          { key: "pay", label: "Record a payment against a liability" },
        ],
      },
      {
        key: "bankAccounts",
        label: "Bank Accounts & Reconciliation Page",
        page: true,
        path: "/admin/accounting/bank-accounts",
        actions: [
          view,
          create,
          { key: "importStatement", label: "Import a bank statement" },
          { key: "match", label: "Match or unmatch a statement line", dangerous: true },
        ],
      },
      {
        key: "fiscalConfig",
        label: "Fiscal Configuration Page",
        page: true,
        path: "/admin/accounting/fiscal-config",
        // The doc's own name for this is "the ERP's accounting control
        // center" — voucher prefixes, default account mappings, closing
        // rules. update is dangerous: a wrong mapping here silently
        // misdirects every future posting that relies on it.
        actions: [view, { key: "update", label: "Change fiscal configuration", dangerous: true }],
      },
    ],
  },
  {
    key: "statements",
    label: "Financial Statements",
    resources: [
      {
        key: "openingBalances",
        label: "Opening Balances Page",
        page: true,
        path: "/admin/opening-balances",
        actions: [view, update],
      },
      {
        key: "generateStatements",
        label: "Generate Statements Page",
        page: true,
        path: "/admin/accounting/statements?tab=generate",
        actions: [view, { key: "generate", label: "Generate Statements" }, exportAct],
      },
      {
        key: "incomeExpenditure",
        label: "Income & Expenditure Page",
        page: true,
        path: "/admin/accounting/statements?tab=income-expenditure",
        actions: [view, exportAct],
      },
      {
        key: "assetsLiabilities",
        label: "Assets & Liabilities Page",
        page: true,
        path: "/admin/accounting/statements?tab=assets-liabilities",
        actions: [view, exportAct],
      },
      {
        key: "otherStatements",
        label: "Trial Balance & Validation Page",
        page: true,
        path: "/admin/accounting/statements?tab=trial-balance",
        actions: [view, exportAct],
      },
      {
        key: "workspace",
        label: "Statements Workspace Page",
        page: true,
        // Merges generateStatements + incomeExpenditure + assetsLiabilities +
        // otherStatements into one tabbed page (design doc §12 Phase 5). The
        // four resources above keep their own permissions — each tab is that
        // same PageClient, gated the same way it always was — this is only
        // the page-level permission for reaching the shell itself.
        path: "/admin/accounting/statements",
        actions: [view],
      },
    ],
  },

  // ── AUDITOR WORKSPACE ────────────────────────────────────────────────────
  // Design doc §8, §12 Phase 5: a read-only surface for an external auditor,
  // with exactly two write actions — raising and resolving a query. No
  // access to any other accounting write permission is implied by anything
  // here; an Auditor role is view + these two only (see
  // lib/rbac/system-role-defaults.js's "Auditor" entry).
  {
    key: "auditor",
    label: "Auditor Workspace",
    resources: [
      {
        key: "workspace",
        label: "Auditor Workspace Page",
        page: true,
        path: "/admin/accounting/auditor",
        // The actual correcting-adjustment write (Auditor Mode) already has
        // its own permission — "audit.report.create", checked in
        // app/api/accounting/audit-trail/route.js's POST — not duplicated
        // here. This resource only covers the two actions that are new in
        // this phase: raising and resolving a query.
        actions: [
          view,
          { key: "raiseQuery", label: "Raise a query against an entry or head" },
          { key: "resolveQuery", label: "Resolve a query" },
        ],
      },
    ],
  },

  // ── COMMERCIAL (shops/offices module) ────────────────────────────────────
  {
    key: "commercial",
    label: "Commercial",
    resources: [
      {
        key: "admin",
        label: "Commercial Page",
        page: true,
        path: "/admin/commercial",
        actions: [view, create, update, del],
      },
    ],
  },

  // ── AMENITIES ─────────────────────────────────────────────────────────────
  {
    key: "amenities",
    label: "Amenities",
    resources: [
      {
        key: "admin",
        label: "Amenities Page",
        page: true,
        path: "/admin/amenities",
        actions: [view, create, update, del],
      },
      // The Clubhouse Manager mobile environment. These are the leaves the
      // /api/v1/clubhouse/* routes check, one per kind of thing a manager does
      // on shift. Separate leaves rather than one "clubhouse.manage" so an
      // Admin can hand out the scan desk without also handing out maintenance
      // or society-wide notices.
      //
      // There is deliberately NO capacity action here. Capacity is
      // configuration-level infrastructure behind amenities.admin.*; no grant
      // in this resource can produce a capacity write.
      {
        key: "clubhouse",
        label: "Clubhouse Manager (mobile)",
        actions: [
          view,
          { key: "checkIn", label: "Scan & record attendance" },
          { key: "operate", label: "Open/close, timings & breaks" },
          { key: "maintenance", label: "Log & update maintenance" },
          { key: "incident", label: "Raise & resolve incidents" },
          { key: "notice", label: "Publish notices" },
        ],
      },
      // Resident amenity cards. Admin custody only: identify a scanned card,
      // and revoke one. Revoking is dangerous — a revoked card is how a
      // resident finds themselves refused at the door.
      {
        key: "memberCard",
        label: "Resident Amenity Cards",
        page: true,
        path: "/admin/amenities/cards",
        actions: [
          view,
          { key: "revoke", label: "Revoke a card", dangerous: true },
        ],
      },
    ],
  },

  // ── MEMBERS ──────────────────────────────────────────────────────────────
  {
    key: "member",
    label: "Members",
    resources: [
      {
        key: "viewMembers",
        label: "View Members Page",
        page: true,
        path: "/admin/view-members",
        actions: [view],
      },
      {
        key: "importMembers",
        label: "Import Members Page",
        page: true,
        path: "/admin/import-members",
        actions: [view],
      },
      {
        key: "profileEditRequests",
        label: "Profile Edit Requests Page",
        page: true,
        path: "/admin/profile-edit-requests",
        actions: [view],
      },
      {
        key: "tenantRequests",
        label: "Tenant Requests Page",
        page: true,
        path: "/admin/tenant-requests",
        actions: [view],
      },

      {
        key: "member",
        label: "Member Records",
        actions: [
          view,
          create,
          update,
          del,
          { key: "import", label: "Import Members", dangerous: true },
          {
            key: "downloadCredentials",
            label: "Download Credentials",
            dangerous: true,
          },
          {
            key: "resetPassword",
            label: "Reset Member Password",
            dangerous: true,
          },
          exportAct,
        ],
      },
      {
        key: "profileEditRequest",
        label: "Profile Edit Requests",
        actions: [
          view,
          { key: "approve", label: "Approve" },
          { key: "reject", label: "Reject" },
        ],
      },
      {
        key: "tenantRequest",
        label: "Tenant Requests",
        actions: [
          view,
          { key: "approve", label: "Approve" },
          { key: "reject", label: "Reject" },
          { key: "confirmMoveOut", label: "Confirm Move-Out", dangerous: true },
        ],
      },
      {
        key: "profile",
        label: "Member Self-Service Profile",
        actions: [
          { key: "viewSelf", label: "View Own Profile" },
          { key: "updateSelf", label: "Update Own Profile" },
        ],
      },
    ],
  },

  // ── COMPLAINTS ───────────────────────────────────────────────────────────
  {
    key: "complaint",
    label: "Complaints",
    resources: [
      {
        key: "admin",
        label: "Complaints Page",
        page: true,
        path: "/admin/complaints",
        actions: [view],
      },
      {
        key: "complaint",
        label: "Complaints",
        actions: [
          view,
          create,
          { key: "reply", label: "Reply" },
          { key: "approve", label: "Approve" },
          { key: "reject", label: "Reject" },
          { key: "close", label: "Close / Auto-close" },
        ],
      },
    ],
  },

  // ── NOTICES ──────────────────────────────────────────────────────────────
  {
    key: "notice",
    label: "Notices",
    resources: [
      {
        key: "admin",
        label: "Notices Page",
        page: true,
        path: "/admin/notices",
        actions: [view],
      },
      { key: "notice", label: "Notices", actions: [view, create, update, del] },
    ],
  },

  // ── VISITORS / SECURITY GATE ─────────────────────────────────────────────
  {
    key: "visitor",
    label: "Visitor Management",
    resources: [
      {
        key: "admin",
        label: "Visitors Page",
        page: true,
        path: "/admin/visitors",
        actions: [view],
      },
      {
        key: "active",
        label: "Active Visitors Page",
        page: true,
        path: "/admin/visitors/active",
        actions: [view],
      },
      {
        key: "log",
        label: "Visitor Log Page",
        page: true,
        path: "/admin/visitors/log",
        actions: [view],
      },
      {
        key: "audit",
        label: "Visitor Audit Page",
        page: true,
        path: "/admin/visitors/audit",
        actions: [view],
      },
      {
        key: "gate",
        label: "Security Gate Console",
        page: true,
        path: "/security/dashboard",
        actions: [view],
      },

      {
        key: "visitor",
        label: "Visitor Records",
        actions: [
          view,
          { key: "enter", label: "Log Entry" },
          { key: "exit", label: "Log Exit" },
          { key: "approve", label: "Approve" },
          { key: "extend", label: "Extend" },
          { key: "offlineEntry", label: "Offline Entry", dangerous: true },
          { key: "guardAdmit", label: "Guard Admit", dangerous: true },
          { key: "sos", label: "Raise SOS" },
        ],
      },
      {
        key: "pass",
        label: "Visitor Passes",
        actions: [view, create, { key: "verify", label: "Verify Pass" }, del],
      },
      {
        key: "blacklist",
        label: "Watchlist Page",
        page: true,
        path: "/admin/blacklist",
        actions: [
          view,
          { key: "add", label: "Add to Blacklist", dangerous: true },
          { key: "remove", label: "Remove", dangerous: true },
        ],
      },
    ],
  },

  // ── SECURITY GUARD MANAGEMENT ────────────────────────────────────────────
  {
    key: "security",
    label: "Security Staff",
    resources: [
      {
        key: "guards",
        label: "Security Guards Page",
        page: true,
        path: "/admin/security-guards",
        actions: [view],
      },
      {
        key: "guard",
        label: "Security Guards",
        actions: [
          view,
          create,
          update,
          del,
          { key: "resetPin", label: "Reset PIN", dangerous: true },
        ],
      },
    ],
  },

  // ── SOCIETY CONFIG ───────────────────────────────────────────────────────
  {
    key: "society",
    label: "Society Configuration",
    resources: [
      {
        key: "databaseManager",
        label: "Database Manager Page",
        page: true,
        path: "/admin/database-manager",
        actions: [view],
      },
      {
        key: "config",
        label: "Society Settings",
        page: true,
        path: "/admin/society-config",
        actions: [
          view,
          { key: "update", label: "Update Society Config", dangerous: true },
        ],
      },
      {
        key: "data",
        label: "Raw Data (Database Manager)",
        actions: [
          view,
          { key: "import", label: "Import Data", dangerous: true },
          exportAct,
          { key: "reset", label: "Reset Entity", dangerous: true },
          del,
        ],
      },
      {
        key: "systemTests",
        label: "System Test Tools Page",
        page: true,
        path: "/admin/accounting-lab",
        // "update" backs both the lab's own write actions AND the ~31
        // accounting/* engine API routes it is currently the only real
        // consumer of (no production admin page exists for those yet —
        // see lib/rbac/page-access-map.js systemTests entry).
        actions: [view, { key: "update", label: "Run / Modify Test Data", dangerous: true }],
      },
    ],
  },

  // ── AUDIT & COMPLIANCE ───────────────────────────────────────────────────
  {
    key: "audit",
    label: "Audit & Compliance",
    resources: [
      {
        key: "page",
        label: "Audit Page",
        page: true,
        path: "/admin/audit",
        actions: [view],
      },
      {
        key: "log",
        label: "Audit Log",
        actions: [{ key: "read", label: "Read Audit Log" }, exportAct],
      },
      { key: "report", label: "Audit Reports", actions: [view, create] },
    ],
  },

  // ── RBAC ADMIN (role & permission management) ────────────────────────────
  {
    key: "rbac",
    label: "Roles & Permissions",
    resources: [
      // Shared page — EVERY authenticated user can view their OWN access here.
      // Granted implicitly to all contexts (see system-role-defaults + member caps).
      {
        key: "myAccess",
        label: "My Roles & Permissions Page",
        page: true,
        path: "/my-access",
        actions: [view],
      },
      // Admin-only role management surface.
      {
        key: "roleManager",
        label: "Role Manager Page",
        page: true,
        path: "/admin/rbac/roles",
        actions: [view],
      },
      {
        key: "role",
        label: "Roles",
        actions: [
          view,
          create,
          update,
          { key: "clone", label: "Clone Role" },
          { key: "delete", label: "Delete Custom Role", dangerous: true },
          {
            key: "restoreDefaults",
            label: "Restore Template Defaults",
            dangerous: true,
          },
        ],
      },
      {
        key: "assignment",
        label: "Role Assignments",
        actions: [
          view,
          { key: "assign", label: "Assign Role", dangerous: true },
          { key: "unassign", label: "Unassign Role", dangerous: true },
        ],
      },
      {
        key: "user",
        label: "User Access Lifecycle",
        actions: [
          view,
          { key: "create", label: "Create Login User" },
          { key: "suspend", label: "Suspend User", dangerous: true },
          { key: "reactivate", label: "Reactivate User" },
        ],
      },
    ],
  },
];

export default PERMISSION_CATALOG;
